name: shoppingo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
  adaptive_icon_foreground: "images/app_icon.png"
  adaptive_icon_background: "#dcf4fb" 
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - images/app_icon.png
    - images/products/laptop/
    - images/products/keyboard/
    - images/products/mouse/
    - images/products/monitor/
    - images/products/mobile/
    - images/products/headphone/